# Generated by Django 3.1.4 on 2020-12-20 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0003_auto_20201220_0821'),
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='deck_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deck.userdeck'),
        ),
    ]
