# Generated by Django 3.1.4 on 2020-12-20 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20201220_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='deck_id',
            new_name='user_deck_id',
        ),
    ]
