# Generated by Django 3.1.4 on 2020-12-20 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_auto_20201220_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='user_deck_id',
            new_name='user_deck',
        ),
    ]
