# Generated by Django 3.1.4 on 2020-12-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0002_userdeck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdeck',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
