# Generated by Django 3.1.4 on 2020-12-20 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0003_auto_20201220_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdeck',
            old_name='deck_id',
            new_name='deck',
        ),
        migrations.RenameField(
            model_name='userdeck',
            old_name='user_id',
            new_name='user',
        ),
    ]
